name: pytorch-CycleGAN-and-pix2pix
channels:
- pytorch
- defaults
dependencies:
- python=3.8
- pytorch=1.10.0
- scipy
- pip
- pip:
  - dominate==2.6.0
  - torchvision==0.11.1
  - pillow==8.4.0
  - numpy==1.19.2
  - visdom==0.1.8.9
